package generate

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/Haroutio/arrsenal/internal/registry"
	"github.com/Haroutio/arrsenal/internal/state"
)

// NetworkName is the one bridge network everything joins; every wired
// connection is a container-name URL on it (DESIGN.md §6).
const NetworkName = "arrsenal"

// header goes on top of every generated file. The YAML body below it is
// marshalled from structs — the header is the only hand-written text.
const header = `# GENERATED BY ARRSENAL — DO NOT EDIT.
# This file is regenerated from %s on every run;
# your edits here will be lost. Put customizations in
# docker-compose.override.yml (same directory) — Compose merges it
# automatically and Arrsenal never touches it.
`

// Artifacts is everything generation produces. Byte-identical for identical
// state — that property is pinned by golden tests, not promised.
type Artifacts struct {
	Compose []byte // docker-compose.yml
	Env     []byte // .env
}

// compose file model — only the subset of the spec Arrsenal emits. Structs,
// never string templating (DESIGN.md §2).
type composeFile struct {
	Name     string             `yaml:"name"`
	Services map[string]service `yaml:"services"`
	Networks map[string]network `yaml:"networks,omitempty"`
}

type service struct {
	Image         string            `yaml:"image"`
	ContainerName string            `yaml:"container_name"`
	Restart       string            `yaml:"restart"`
	User          string            `yaml:"user,omitempty"`
	CapAdd        []string          `yaml:"cap_add,omitempty"`
	NetworkMode   string            `yaml:"network_mode,omitempty"`
	Networks      []string          `yaml:"networks,omitempty"`
	Environment   map[string]string `yaml:"environment,omitempty"`
	EnvFile       []string          `yaml:"env_file,omitempty"`
	Ports         []portMapping     `yaml:"ports,omitempty"`
	Volumes       []string          `yaml:"volumes,omitempty"`
	Devices       []string          `yaml:"devices,omitempty"`
	DependsOn     []string          `yaml:"depends_on,omitempty"`
	Deploy        *deploy           `yaml:"deploy,omitempty"`
}

// portMapping always marshals double-quoted: unquoted digit:digit scalars are
// a YAML 1.1 sexagesimal trap (a hypothetical `53:53` reads as an integer in
// 1.1 parsers), and the compose docs say to quote port mappings for exactly
// that reason.
type portMapping string

// MarshalYAML emits the mapping as a quoted scalar.
func (p portMapping) MarshalYAML() ([]byte, error) {
	return []byte(strconv.Quote(string(p))), nil
}

type deploy struct {
	Resources resources `yaml:"resources"`
}

type resources struct {
	Reservations reservations `yaml:"reservations"`
}

type reservations struct {
	Devices []deviceReservation `yaml:"devices"`
}

type deviceReservation struct {
	Driver       string   `yaml:"driver"`
	Count        string   `yaml:"count"`
	Capabilities []string `yaml:"capabilities"`
}

type network struct {
	Driver string `yaml:"driver"`
}

// Render produces the artifacts for a state. The state carries everything;
// rendering is a pure function of it plus the registry. statePath is only
// named in the header so users know what to re-run.
func Render(s *state.State, statePath string) (Artifacts, error) {
	if err := s.Validate(); err != nil {
		return Artifacts{}, fmt.Errorf("refusing to render invalid state: %w", err)
	}
	if len(s.Apps) == 0 {
		return Artifacts{}, fmt.Errorf("no apps selected — nothing to render")
	}

	services := map[string]service{}
	for _, id := range s.Apps {
		app, _ := registry.ByID(id) // state.Validate guarantees existence
		services[id] = renderService(s, app)
	}
	if s.VPNEnabled() {
		services["gluetun"] = renderGluetun(s)
	}

	cf := composeFile{
		Name:     "arrsenal",
		Services: services,
		Networks: map[string]network{NetworkName: {Driver: "bridge"}},
	}
	body, err := yaml.Marshal(cf)
	if err != nil {
		return Artifacts{}, fmt.Errorf("marshalling compose file: %w", err)
	}

	return Artifacts{
		Compose: append(fileHeader(statePath), body...),
		Env:     append(fileHeader(statePath), envBody(s)...),
	}, nil
}

func fileHeader(statePath string) []byte {
	return []byte(fmt.Sprintf(header, statePath))
}

func renderService(s *state.State, app registry.App) service {
	svc := service{
		Image:         app.ImageRef(),
		ContainerName: app.ID,
		Restart:       "unless-stopped",
		Environment:   map[string]string{"TZ": "${TZ}"},
		Volumes:       renderVolumes(s, app),
	}

	switch app.Identity {
	case registry.IdentityEnvPUIDGID:
		svc.Environment["PUID"] = "${PUID}"
		svc.Environment["PGID"] = "${PGID}"
		svc.Environment["UMASK"] = "${UMASK}"
	case registry.IdentityUserDirective:
		svc.User = "${PUID}:${PGID}"
	case registry.IdentityNone:
		// image manages its own user
	}
	for k, v := range app.Env {
		svc.Environment[k] = v
	}
	if app.WebPortEnv != "" {
		// The env var tracks the effective in-container web port (see
		// state.WebPorts); under a remap both move together.
		_, container := s.WebPorts(app)
		svc.Environment[app.WebPortEnv] = strconv.Itoa(container)
	}
	if app.ID == "plex" {
		// The claim token (plex.tv/claim, 4-minute expiry) is a per-run
		// value: cmd writes it into this 0600 env-file right before
		// bring-up — never into the state or these artifacts (issue #26).
		svc.EnvFile = []string{"${APPDATA}/plex/claim.env"}
	}

	switch {
	case app.ID == "qbittorrent" && s.VPNEnabled():
		// qBittorrent lives inside gluetun's network namespace: every packet
		// rides the tunnel or nowhere (the kill switch is structural). Its
		// ports are published BY gluetun; on the bridge it answers at
		// gluetun:<port> (issue #27).
		svc.NetworkMode = "service:gluetun"
		svc.DependsOn = []string{"gluetun"}
	case s.HostNetworked(app.ID):
		// Host networking publishes nothing and joins no bridge network;
		// DLNA/discovery is the point (DESIGN.md §6).
		svc.NetworkMode = "host"
	default:
		svc.Networks = []string{NetworkName}
		svc.Ports = renderPorts(s, app)
	}

	if app.GPU {
		applyGPU(s, &svc)
	}
	return svc
}

func renderPorts(s *state.State, app registry.App) []portMapping {
	webHost, webContainer := s.WebPorts(app)
	out := []portMapping{portMapping(fmt.Sprintf("%d:%d", webHost, webContainer))}
	for _, p := range app.ExtraPorts {
		entry := fmt.Sprintf("%d:%d", s.HostPort(app, p), p.Container)
		if p.Protocol == "udp" {
			entry += "/udp"
		}
		out = append(out, portMapping(entry))
	}
	return out
}

// downloadSubs are the trees that follow the downloads root when storage is
// split (issue #59). Media always follows the data root.
var downloadSubs = map[string]bool{"usenet": true, "torrents": true}

func renderVolumes(s *state.State, app registry.App) []string {
	var out []string
	for _, m := range app.Mounts {
		switch m.Kind {
		case registry.SourceAppdata:
			out = append(out, mountEntry("${APPDATA}/"+app.ID, m.Target, m.ReadOnly))
		case registry.SourceHost:
			out = append(out, mountEntry(m.Sub, m.Target, m.ReadOnly))
		case registry.SourceData:
			switch {
			case m.Sub == "" && !s.SplitStorage():
				// The classic single mount: downloads + media on one
				// filesystem, imports are hardlinks.
				out = append(out, mountEntry("${DATA}", m.Target, m.ReadOnly))
			case m.Sub == "" && s.SplitStorage():
				// The full-root mount cannot span two filesystems; expand it
				// into the three fixed container paths so every app still
				// sees the same /data layout (issue #59).
				out = append(out,
					mountEntry("${DATA}/media", m.Target+"/media", m.ReadOnly),
					mountEntry("${DOWNLOADS}/usenet", m.Target+"/usenet", m.ReadOnly),
					mountEntry("${DOWNLOADS}/torrents", m.Target+"/torrents", m.ReadOnly),
				)
			case downloadSubs[m.Sub] && s.SplitStorage():
				out = append(out, mountEntry("${DOWNLOADS}/"+m.Sub, m.Target, m.ReadOnly))
			default:
				out = append(out, mountEntry("${DATA}/"+m.Sub, m.Target, m.ReadOnly))
			}
		}
	}
	return out
}

func mountEntry(src, target string, readOnly bool) string {
	entry := src + ":" + target
	if readOnly {
		entry += ":ro"
	}
	return entry
}

// applyGPU wires the transcode device per mode (DESIGN.md §8). Group handling
// for /dev/dri (render group membership inside the container) is finalized by
// the GPU detection issue (#11) together with preflight; the device plumbing
// is stable.
func applyGPU(s *state.State, svc *service) {
	switch s.GPU {
	case state.GPUNvidia:
		svc.Deploy = &deploy{Resources: resources{Reservations: reservations{
			Devices: []deviceReservation{{Driver: "nvidia", Count: "all", Capabilities: []string{"gpu"}}},
		}}}
		// Older container toolkits default the driver capabilities to
		// compute+utility — no video — which silently breaks NVENC inside
		// the container. Explicit is the only portable setting (it is also
		// what Jellyfin's own docs prescribe).
		svc.Environment["NVIDIA_DRIVER_CAPABILITIES"] = "all"
	case state.GPUIntel, state.GPUAMD:
		svc.Devices = []string{"/dev/dri:/dev/dri"}
	case state.GPUNone:
		// CPU transcode: nothing to add.
	}
}

// renderGluetun is the VPN tunnel (issue #27): NET_ADMIN + /dev/net/tun, the
// provider via plain env, and the CREDENTIALS via a separate 0600 env-file
// under gluetun's appdata — never in the world-readable artifacts. It
// publishes qBittorrent's web port on the tunnel container.
func renderGluetun(s *state.State) service {
	env := map[string]string{
		"TZ":                   "${TZ}",
		"VPN_SERVICE_PROVIDER": s.VPN.Provider,
		"VPN_TYPE":             "wireguard",
	}
	if s.VPN.Countries != "" {
		env["SERVER_COUNTRIES"] = s.VPN.Countries
	}
	svc := service{
		Image:         "qmcgaw/gluetun:latest",
		ContainerName: "gluetun",
		Restart:       "unless-stopped",
		CapAdd:        []string{"NET_ADMIN"},
		Devices:       []string{"/dev/net/tun:/dev/net/tun"},
		Networks:      []string{NetworkName},
		Environment:   env,
		EnvFile:       []string{"${APPDATA}/gluetun/credentials.env"},
		Volumes:       []string{"${APPDATA}/gluetun:/gluetun"},
	}
	if qb, ok := registry.ByID("qbittorrent"); ok {
		host, container := s.WebPorts(qb)
		svc.Ports = []portMapping{portMapping(fmt.Sprintf("%d:%d", host, container))}
	}
	return svc
}

// envBody renders .env in fixed order. Values the containers consume come
// from here; the compose file only ever references ${VARS} so a user reading
// either file sees the same names the seed ecosystem uses.
func envBody(s *state.State) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "PUID=%d\n", s.PUID)
	fmt.Fprintf(&b, "PGID=%d\n", s.PGID)
	fmt.Fprintf(&b, "TZ=%s\n", s.TZ)
	fmt.Fprintf(&b, "UMASK=%s\n", s.Umask)
	fmt.Fprintf(&b, "DATA=%s\n", s.DataRoot)
	if s.SplitStorage() {
		fmt.Fprintf(&b, "DOWNLOADS=%s\n", s.DownloadsRoot)
	}
	fmt.Fprintf(&b, "APPDATA=%s\n", s.AppdataRoot)
	return []byte(b.String())
}
