package generate

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/Haroutio/arrsenal/internal/registry"
	"github.com/Haroutio/arrsenal/internal/state"
)

// NetworkName is the one bridge network everything joins; every wired
// connection is a container-name URL on it (DESIGN.md §6).
const NetworkName = "arrsenal"

// header goes on top of every generated file. The YAML body below it is
// marshalled from structs — the header is the only hand-written text.
const header = `# GENERATED BY ARRSENAL — DO NOT EDIT.
# This file is regenerated from %s on every run;
# your edits here will be lost. Put customizations in
# docker-compose.override.yml (same directory) — Compose merges it
# automatically and Arrsenal never touches it.
`

// Artifacts is everything generation produces. Byte-identical for identical
// state — that property is pinned by golden tests, not promised.
type Artifacts struct {
	Compose []byte // docker-compose.yml
	Env     []byte // .env
}

// compose file model — only the subset of the spec Arrsenal emits. Structs,
// never string templating (DESIGN.md §2).
type composeFile struct {
	Name     string             `yaml:"name"`
	Services map[string]service `yaml:"services"`
	Networks map[string]network `yaml:"networks,omitempty"`
}

type service struct {
	Image         string            `yaml:"image"`
	ContainerName string            `yaml:"container_name"`
	Restart       string            `yaml:"restart"`
	User          string            `yaml:"user,omitempty"`
	NetworkMode   string            `yaml:"network_mode,omitempty"`
	Networks      []string          `yaml:"networks,omitempty"`
	Environment   map[string]string `yaml:"environment,omitempty"`
	Ports         []portMapping     `yaml:"ports,omitempty"`
	Volumes       []string          `yaml:"volumes,omitempty"`
	Devices       []string          `yaml:"devices,omitempty"`
	Deploy        *deploy           `yaml:"deploy,omitempty"`
}

// portMapping always marshals double-quoted: unquoted digit:digit scalars are
// a YAML 1.1 sexagesimal trap (a hypothetical `53:53` reads as an integer in
// 1.1 parsers), and the compose docs say to quote port mappings for exactly
// that reason.
type portMapping string

// MarshalYAML emits the mapping as a quoted scalar.
func (p portMapping) MarshalYAML() ([]byte, error) {
	return []byte(strconv.Quote(string(p))), nil
}

type deploy struct {
	Resources resources `yaml:"resources"`
}

type resources struct {
	Reservations reservations `yaml:"reservations"`
}

type reservations struct {
	Devices []deviceReservation `yaml:"devices"`
}

type deviceReservation struct {
	Driver       string   `yaml:"driver"`
	Count        string   `yaml:"count"`
	Capabilities []string `yaml:"capabilities"`
}

type network struct {
	Driver string `yaml:"driver"`
}

// Render produces the artifacts for a state. The state carries everything;
// rendering is a pure function of it plus the registry. statePath is only
// named in the header so users know what to re-run.
func Render(s *state.State, statePath string) (Artifacts, error) {
	if err := s.Validate(); err != nil {
		return Artifacts{}, fmt.Errorf("refusing to render invalid state: %w", err)
	}
	if len(s.Apps) == 0 {
		return Artifacts{}, fmt.Errorf("no apps selected — nothing to render")
	}

	services := map[string]service{}
	for _, id := range s.Apps {
		app, _ := registry.ByID(id) // state.Validate guarantees existence
		services[id] = renderService(s, app)
	}

	cf := composeFile{
		Name:     "arrsenal",
		Services: services,
		Networks: map[string]network{NetworkName: {Driver: "bridge"}},
	}
	body, err := yaml.Marshal(cf)
	if err != nil {
		return Artifacts{}, fmt.Errorf("marshalling compose file: %w", err)
	}

	return Artifacts{
		Compose: append(fileHeader(statePath), body...),
		Env:     append(fileHeader(statePath), envBody(s)...),
	}, nil
}

func fileHeader(statePath string) []byte {
	return []byte(fmt.Sprintf(header, statePath))
}

func renderService(s *state.State, app registry.App) service {
	svc := service{
		Image:         app.ImageRef(),
		ContainerName: app.ID,
		Restart:       "unless-stopped",
		Environment:   map[string]string{"TZ": "${TZ}"},
		Volumes:       renderVolumes(app),
	}

	switch app.Identity {
	case registry.IdentityEnvPUIDGID:
		svc.Environment["PUID"] = "${PUID}"
		svc.Environment["PGID"] = "${PGID}"
		svc.Environment["UMASK"] = "${UMASK}"
	case registry.IdentityUserDirective:
		svc.User = "${PUID}:${PGID}"
	case registry.IdentityNone:
		// image manages its own user
	}
	for k, v := range app.Env {
		svc.Environment[k] = v
	}
	if app.WebPortEnv != "" {
		// The env var tracks the effective in-container web port (see
		// state.WebPorts); under a remap both move together.
		_, container := s.WebPorts(app)
		svc.Environment[app.WebPortEnv] = strconv.Itoa(container)
	}

	if s.HostNetworked(app.ID) {
		// Host networking publishes nothing and joins no bridge network;
		// DLNA/discovery is the point (DESIGN.md §6).
		svc.NetworkMode = "host"
	} else {
		svc.Networks = []string{NetworkName}
		svc.Ports = renderPorts(s, app)
	}

	if app.GPU {
		applyGPU(s, &svc)
	}
	return svc
}

func renderPorts(s *state.State, app registry.App) []portMapping {
	webHost, webContainer := s.WebPorts(app)
	out := []portMapping{portMapping(fmt.Sprintf("%d:%d", webHost, webContainer))}
	for _, p := range app.ExtraPorts {
		entry := fmt.Sprintf("%d:%d", s.HostPort(app, p), p.Container)
		if p.Protocol == "udp" {
			entry += "/udp"
		}
		out = append(out, portMapping(entry))
	}
	return out
}

func renderVolumes(app registry.App) []string {
	var out []string
	for _, m := range app.Mounts {
		var src string
		switch m.Kind {
		case registry.SourceAppdata:
			src = "${APPDATA}/" + app.ID
		case registry.SourceData:
			src = "${DATA}"
			if m.Sub != "" {
				src += "/" + m.Sub
			}
		case registry.SourceHost:
			src = m.Sub
		}
		entry := src + ":" + m.Target
		if m.ReadOnly {
			entry += ":ro"
		}
		out = append(out, entry)
	}
	return out
}

// applyGPU wires the transcode device per mode (DESIGN.md §8). Group handling
// for /dev/dri (render group membership inside the container) is finalized by
// the GPU detection issue (#11) together with preflight; the device plumbing
// is stable.
func applyGPU(s *state.State, svc *service) {
	switch s.GPU {
	case state.GPUNvidia:
		svc.Deploy = &deploy{Resources: resources{Reservations: reservations{
			Devices: []deviceReservation{{Driver: "nvidia", Count: "all", Capabilities: []string{"gpu"}}},
		}}}
		// Older container toolkits default the driver capabilities to
		// compute+utility — no video — which silently breaks NVENC inside
		// the container. Explicit is the only portable setting (it is also
		// what Jellyfin's own docs prescribe).
		svc.Environment["NVIDIA_DRIVER_CAPABILITIES"] = "all"
	case state.GPUIntel, state.GPUAMD:
		svc.Devices = []string{"/dev/dri:/dev/dri"}
	case state.GPUNone:
		// CPU transcode: nothing to add.
	}
}

// envBody renders .env in fixed order. Values the containers consume come
// from here; the compose file only ever references ${VARS} so a user reading
// either file sees the same names the seed ecosystem uses.
func envBody(s *state.State) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "PUID=%d\n", s.PUID)
	fmt.Fprintf(&b, "PGID=%d\n", s.PGID)
	fmt.Fprintf(&b, "TZ=%s\n", s.TZ)
	fmt.Fprintf(&b, "UMASK=%s\n", s.Umask)
	fmt.Fprintf(&b, "DATA=%s\n", s.DataRoot)
	fmt.Fprintf(&b, "APPDATA=%s\n", s.AppdataRoot)
	return []byte(b.String())
}
