// Package quality generates Recyclarr configuration from plain-language
// answers, mapping them onto TRaSH-guide templates (issue #60). Arrsenal
// deliberately does NOT reimplement the TRaSH custom-format database —
// Recyclarr consumes the guides' own data and stays current; our job is the
// friendly layer that picks the right templates and runs the sync.
package quality

import (
	"fmt"
	"strings"
)

// Answers are the quality choices, in user language.
type Answers struct {
	// Resolution: "1080p" or "2160p".
	Resolution string
	// Source: "bluray-web" (the standard tier) or "remux" (quality-first,
	// much larger files). The distinction shapes Radarr's profile; Sonarr's
	// TRaSH templates are WEB-based either way.
	Source string
	// Anime adds the dedicated anime profiles alongside the main ones.
	Anime bool
}

// Validate rejects unknown enum values with the accepted ones named.
func (a Answers) Validate() error {
	switch a.Resolution {
	case "1080p", "2160p":
	default:
		return fmt.Errorf("resolution %q: pick 1080p or 2160p", a.Resolution)
	}
	switch a.Source {
	case "bluray-web", "remux":
	default:
		return fmt.Errorf("source %q: pick bluray-web or remux", a.Source)
	}
	return nil
}

// Instance is one arr as Recyclarr should reach it: the container-name URL
// and the API key the wiring engine already read.
type Instance struct {
	BaseURL string
	APIKey  string
}

// Include names verified against recyclarr/config-templates includes.json
// at HEAD — these are what `include: - template:` resolves against (NOT the
// starter-config filenames, which live in a different registry; learned by a
// live sync failure). Each choice is the canonical TRaSH triad:
// quality-definition + quality-profile + custom-formats.
func sonarrTemplates(a Answers) []string {
	res := "1080p"
	if a.Resolution == "2160p" {
		res = "2160p"
	}
	t := []string{
		"sonarr-quality-definition-series",
		"sonarr-v4-quality-profile-web-" + res,
		"sonarr-v4-custom-formats-web-" + res,
	}
	if a.Anime {
		t = append(t,
			"sonarr-v4-quality-profile-anime",
			"sonarr-v4-custom-formats-anime",
		)
	}
	return t
}

func radarrTemplates(a Answers) []string {
	var main string
	switch {
	case a.Source == "remux" && a.Resolution == "2160p":
		main = "remux-web-2160p"
	case a.Source == "remux":
		main = "remux-web-1080p"
	case a.Resolution == "2160p":
		main = "uhd-bluray-web"
	default:
		main = "hd-bluray-web"
	}
	t := []string{
		"radarr-quality-definition-movie",
		"radarr-quality-profile-" + main,
		"radarr-custom-formats-" + main,
	}
	if a.Anime {
		t = append(t,
			"radarr-quality-profile-anime",
			"radarr-custom-formats-anime",
		)
	}
	return t
}

// RecyclarrConfig renders recyclarr.yml for the given instances. Instances
// are optional (nil = app not selected); at least one is required. Output is
// deterministic; the API keys appear here by necessity — the file lands 0600
// under Arrsenal's appdata (the caller's job), like every other secret file.
func RecyclarrConfig(a Answers, sonarr, radarr *Instance) ([]byte, error) {
	if err := a.Validate(); err != nil {
		return nil, err
	}
	if sonarr == nil && radarr == nil {
		return nil, fmt.Errorf("nothing to configure: neither Sonarr nor Radarr is available")
	}

	var b strings.Builder
	b.WriteString("# GENERATED BY ARRSENAL — regenerated every run from your quality answers.\n")
	writeInstance(&b, "sonarr", sonarr, sonarrTemplates(a))
	writeInstance(&b, "radarr", radarr, radarrTemplates(a))
	return []byte(b.String()), nil
}

func writeInstance(b *strings.Builder, kind string, inst *Instance, templates []string) {
	if inst == nil {
		return
	}
	fmt.Fprintf(b, "%s:\n", kind)
	fmt.Fprintf(b, "  %s:\n", kind)
	fmt.Fprintf(b, "    base_url: %s\n", inst.BaseURL)
	fmt.Fprintf(b, "    api_key: %s\n", inst.APIKey)
	b.WriteString("    include:\n")
	for _, t := range templates {
		fmt.Fprintf(b, "      - template: %s\n", t)
	}
}
