// Package quality generates Recyclarr configuration from plain-language
// answers, mapping them onto TRaSH-guide quality profiles (issue #60).
// Arrsenal deliberately does NOT reimplement the TRaSH custom-format
// database — Recyclarr consumes the guides' own data and stays current; our
// job is the friendly layer that picks the right profiles and runs the sync.
package quality

import (
	"fmt"
	"strings"
)

// Answers are the quality choices, in user language.
type Answers struct {
	// Resolution: "1080p" or "2160p".
	Resolution string
	// Source: "bluray-web" (the standard tier) or "remux" (quality-first,
	// much larger files). The distinction shapes Radarr's profile; Sonarr's
	// TRaSH profiles are WEB-based either way.
	Source string
	// Anime adds the dedicated anime profile alongside the main one.
	Anime bool
}

// Validate rejects unknown enum values with the accepted ones named.
func (a Answers) Validate() error {
	switch a.Resolution {
	case "1080p", "2160p":
	default:
		return fmt.Errorf("resolution %q: pick 1080p or 2160p", a.Resolution)
	}
	switch a.Source {
	case "bluray-web", "remux":
	default:
		return fmt.Errorf("source %q: pick bluray-web or remux", a.Source)
	}
	return nil
}

// Instance is one arr as Recyclarr should reach it: the container-name URL
// and the API key the wiring engine already read.
type Instance struct {
	BaseURL string
	APIKey  string
}

// profile is one TRaSH-guide quality profile, addressed the way Recyclarr v8
// does: by its trash_id, a stable identifier the guides never change. The
// name is the guide's display name — it becomes the profile's name in the
// arr, and a comment for humans reading the generated file.
//
// Recyclarr v8 dropped the v7 include-template mechanism (its registry is
// empty on the v8 branch — learned by a live sync failure); the official v8
// templates are standalone configs whose entire payload is a
// quality_definition plus these trash_id references. We render the same
// schema directly; the IDs below are copied from those templates.
type profile struct {
	TrashID string
	Name    string
}

func sonarrProfiles(a Answers) []profile {
	main := profile{"72dae194fc92bf828f32cde7744e51a1", "WEB-1080p"}
	if a.Resolution == "2160p" {
		main = profile{"d1498e7d189fbe6c7110ceaabb7473e6", "WEB-2160p"}
	}
	p := []profile{main}
	if a.Anime {
		p = append(p, profile{"20e0fc959f1f1704bed501f23bdae76f", "[Anime] Remux-1080p"})
	}
	return p
}

func radarrProfiles(a Answers) []profile {
	var main profile
	switch {
	case a.Source == "remux" && a.Resolution == "2160p":
		main = profile{"fd161a61e3ab826d3a22d53f935696dd", "Remux + WEB 2160p"}
	case a.Source == "remux":
		main = profile{"9ca12ea80aa55ef916e3751f4b874151", "Remux + WEB 1080p"}
	case a.Resolution == "2160p":
		main = profile{"64fb5f9858489bdac2af690e27c8f42f", "UHD Bluray + WEB"}
	default:
		main = profile{"d1d67249d3890e49bc12e275d989a7e9", "HD Bluray + WEB"}
	}
	p := []profile{main}
	if a.Anime {
		p = append(p, profile{"722b624f9af1e492284c4bc842153a38", "[Anime] Remux-1080p"})
	}
	return p
}

// RecyclarrConfig renders recyclarr.yml for the given instances. Instances
// are optional (nil = app not selected); at least one is required. Output is
// deterministic; the API keys appear here by necessity — the file lands 0600
// under Arrsenal's appdata (the caller's job), like every other secret file.
func RecyclarrConfig(a Answers, sonarr, radarr *Instance) ([]byte, error) {
	if err := a.Validate(); err != nil {
		return nil, err
	}
	if sonarr == nil && radarr == nil {
		return nil, fmt.Errorf("nothing to configure: neither Sonarr nor Radarr is available")
	}

	var b strings.Builder
	b.WriteString("# GENERATED BY ARRSENAL — regenerated every run from your quality answers.\n")
	// quality_definition types: an instance takes exactly one, so the main
	// choice wins; the anime profile rides alongside on the same definition.
	writeInstance(&b, "sonarr", "series", sonarr, sonarrProfiles(a))
	writeInstance(&b, "radarr", "movie", radarr, radarrProfiles(a))
	return []byte(b.String()), nil
}

func writeInstance(b *strings.Builder, kind, defType string, inst *Instance, profiles []profile) {
	if inst == nil {
		return
	}
	fmt.Fprintf(b, "%s:\n", kind)
	fmt.Fprintf(b, "  %s:\n", kind)
	fmt.Fprintf(b, "    base_url: %s\n", inst.BaseURL)
	fmt.Fprintf(b, "    api_key: %s\n", inst.APIKey)
	b.WriteString("    quality_definition:\n")
	fmt.Fprintf(b, "      type: %s\n", defType)
	b.WriteString("    quality_profiles:\n")
	for _, p := range profiles {
		fmt.Fprintf(b, "      - trash_id: %s # %s\n", p.TrashID, p.Name)
		b.WriteString("        reset_unmatched_scores:\n")
		b.WriteString("          enabled: true\n")
	}
}
